-- ============================================================
-- PadelHouse - Full Database Schema Export
-- Project: vslisxnahktqaifdurcu
-- Date: 2026-02-25
-- ============================================================

-- ============================================================
-- 1. EXTENSIONS
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- 2. ENUMS
-- ============================================================
CREATE TYPE public.user_role AS ENUM ('JOUEUR', 'GERANT', 'EMPLOYE');
CREATE TYPE public.reservation_status AS ENUM ('PENDING', 'CONFIRMED', 'CANCELED', 'EXPIRED', 'PAID');
CREATE TYPE public.event_category AS ENUM ('TOURNOI', 'FORMATION', 'SOCIAL', 'ANIMATION', 'COMPETITION', 'AUTRE');
CREATE TYPE public.event_status AS ENUM ('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED');

-- ============================================================
-- 3. TABLES
-- ============================================================

-- profiles
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id),
  email TEXT NOT NULL UNIQUE,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  birth_date DATE NOT NULL,
  gender TEXT CHECK (gender = ANY (ARRAY['M', 'F', 'O'])),
  role user_role NOT NULL DEFAULT 'JOUEUR'::user_role,
  phone TEXT,
  points INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- terrains
CREATE TABLE public.terrains (
  id BIGSERIAL PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- time_slots
CREATE TABLE public.time_slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  price INTEGER NOT NULL DEFAULT 10000,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT time_slots_unique UNIQUE (start_time, end_time)
);

-- clients
CREATE TABLE public.clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- reservations
CREATE TABLE public.reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  terrain_id BIGINT NOT NULL REFERENCES public.terrains(id),
  time_slot_id BIGINT NOT NULL REFERENCES public.time_slots(id),
  reservation_date DATE NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id),
  status reservation_status NOT NULL DEFAULT 'CONFIRMED'::reservation_status,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  client_id UUID REFERENCES public.clients(id),
  CONSTRAINT reservations_user_id_profiles_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);

-- otp_codes
CREATE TABLE public.otp_codes (
  id BIGSERIAL PRIMARY KEY,
  email TEXT NOT NULL,
  code TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  verified BOOLEAN NOT NULL DEFAULT false,
  attempts INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- coaches
CREATE TABLE public.coaches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  image_url TEXT,
  bio TEXT,
  is_active BOOLEAN DEFAULT true,
  price_1h_solo INTEGER NOT NULL DEFAULT 0,
  price_1h30_solo INTEGER NOT NULL DEFAULT 0,
  price_1h_duo INTEGER NOT NULL DEFAULT 0,
  price_1h30_duo INTEGER NOT NULL DEFAULT 0,
  price_1h_trio INTEGER NOT NULL DEFAULT 0,
  price_1h30_trio INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- employee_profiles (RBAC)
CREATE TABLE public.employee_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR NOT NULL UNIQUE,
  display_name VARCHAR NOT NULL,
  description TEXT,
  base_route VARCHAR NOT NULL DEFAULT '/',
  hierarchy_level INTEGER NOT NULL DEFAULT 10,
  is_system BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE public.employee_profiles IS 'Profils applicatifs (rôles) avec permissions et route de base après connexion';

-- employees
CREATE TABLE public.employees (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  full_name VARCHAR,
  role VARCHAR DEFAULT 'admin',
  is_active BOOLEAN DEFAULT true,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  profile_id UUID REFERENCES public.employee_profiles(id)
);

-- permissions
CREATE TABLE public.permissions (
  id VARCHAR PRIMARY KEY,
  display_name VARCHAR NOT NULL,
  description TEXT,
  category VARCHAR NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0
);

-- profile_permissions (join table)
CREATE TABLE public.profile_permissions (
  profile_id UUID NOT NULL REFERENCES public.employee_profiles(id),
  permission_id VARCHAR NOT NULL REFERENCES public.permissions(id),
  PRIMARY KEY (profile_id, permission_id)
);

-- payment_methods
CREATE TABLE public.payment_methods (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL UNIQUE,
  display_name VARCHAR NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- reservation_payments
CREATE TABLE public.reservation_payments (
  id SERIAL PRIMARY KEY,
  reservation_id INTEGER NOT NULL REFERENCES public.reservations(id),
  payment_method_id INTEGER NOT NULL REFERENCES public.payment_methods(id),
  amount NUMERIC NOT NULL,
  amount_received NUMERIC DEFAULT 0,
  amount_returned NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- app_settings
CREATE TABLE public.app_settings (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  business_name TEXT DEFAULT 'Padel House',
  business_phone TEXT,
  business_email TEXT,
  business_address TEXT,
  opening_time TIME DEFAULT '08:00:00',
  closing_time TIME DEFAULT '23:00:00',
  min_advance_booking INTEGER DEFAULT 1,
  max_advance_booking INTEGER DEFAULT 14,
  cancellation_deadline INTEGER DEFAULT 24,
  currency TEXT DEFAULT 'FCFA',
  notifications_enabled BOOLEAN DEFAULT true,
  email_notifications BOOLEAN DEFAULT true,
  sms_notifications BOOLEAN DEFAULT false,
  manual_reservation_user_id UUID REFERENCES public.profiles(id),
  security_code TEXT DEFAULT '0451373',
  default_tax_rate NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- reclamations
CREATE TABLE public.reclamations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id),
  subject VARCHAR NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR NOT NULL DEFAULT 'general'
    CHECK (category IN ('general', 'reservation', 'terrain', 'paiement', 'autre')),
  status VARCHAR NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'in_progress', 'resolved', 'rejected')),
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  resolved_at TIMESTAMPTZ,
  admin_response TEXT
);

-- expense_types
CREATE TABLE public.expense_types (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- expenses
CREATE TABLE public.expenses (
  id SERIAL PRIMARY KEY,
  expense_type_id INTEGER REFERENCES public.expense_types(id),
  amount NUMERIC NOT NULL,
  description TEXT,
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_by VARCHAR,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- events
CREATE TABLE public.events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  subtitle TEXT,
  description TEXT NOT NULL,
  long_description TEXT,
  category event_category NOT NULL DEFAULT 'AUTRE'::event_category,
  status event_status NOT NULL DEFAULT 'DRAFT'::event_status,
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  location TEXT NOT NULL DEFAULT 'PadelHouse Club',
  cover_image_url TEXT,
  is_featured BOOLEAN NOT NULL DEFAULT false,
  display_order INTEGER NOT NULL DEFAULT 0,
  tags TEXT[] DEFAULT '{}',
  price_info TEXT,
  is_free BOOLEAN NOT NULL DEFAULT true,
  created_by UUID REFERENCES auth.users(id),
  contact_phone TEXT DEFAULT '+2250799998888',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- event_images
CREATE TABLE public.event_images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID NOT NULL REFERENCES public.events(id),
  image_url TEXT NOT NULL,
  caption TEXT,
  display_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- POS (Point of Sale) TABLES
-- ============================================================

-- pos_categories
CREATE TABLE public.pos_categories (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT,
  color TEXT,
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- pos_products
CREATE TABLE public.pos_products (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  category_id INTEGER REFERENCES public.pos_categories(id),
  price NUMERIC NOT NULL DEFAULT 0,
  cost_price NUMERIC DEFAULT 0,
  image_url TEXT,
  is_available BOOLEAN DEFAULT true,
  stock_quantity INTEGER DEFAULT 0,
  min_stock_alert INTEGER DEFAULT 5,
  product_type TEXT NOT NULL DEFAULT 'bien'
    CHECK (product_type IN ('bien', 'service')),
  tax_rate NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- pos_tables
CREATE TABLE public.pos_tables (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  capacity INTEGER NOT NULL DEFAULT 2,
  position_x INTEGER NOT NULL DEFAULT 0,
  position_y INTEGER NOT NULL DEFAULT 0,
  shape TEXT NOT NULL DEFAULT 'round'
    CHECK (shape IN ('round', 'square', 'rectangle')),
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- pos_cash_register_sessions
CREATE TABLE public.pos_cash_register_sessions (
  id SERIAL PRIMARY KEY,
  employee_name TEXT NOT NULL,
  opening_amount NUMERIC NOT NULL DEFAULT 0,
  closing_amount NUMERIC,
  opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'open',
  notes TEXT
);

-- pos_orders
CREATE TABLE public.pos_orders (
  id SERIAL PRIMARY KEY,
  session_id INTEGER REFERENCES public.pos_cash_register_sessions(id),
  order_number TEXT,
  order_type TEXT DEFAULT 'table'
    CHECK (order_type IN ('table', 'terrain')),
  table_id INTEGER REFERENCES public.pos_tables(id),
  terrain_id BIGINT REFERENCES public.terrains(id),
  time_slot_id BIGINT REFERENCES public.time_slots(id),
  reservation_id BIGINT REFERENCES public.reservations(id),
  client_name TEXT,
  subtotal NUMERIC NOT NULL DEFAULT 0,
  tax_amount NUMERIC NOT NULL DEFAULT 0,
  total NUMERIC NOT NULL DEFAULT 0,
  discount NUMERIC DEFAULT 0,
  payment_method TEXT DEFAULT 'cash'
    CHECK (payment_method IN ('cash', 'card', 'mobile_money', 'mixed')),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- pos_order_items
CREATE TABLE public.pos_order_items (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES public.pos_orders(id),
  product_id INTEGER NOT NULL REFERENCES public.pos_products(id),
  quantity INTEGER NOT NULL DEFAULT 1,
  unit_price NUMERIC NOT NULL DEFAULT 0,
  total_price NUMERIC NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- pos_order_payments
CREATE TABLE public.pos_order_payments (
  id SERIAL PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES public.pos_orders(id),
  payment_method_id INTEGER NOT NULL REFERENCES public.payment_methods(id),
  amount NUMERIC NOT NULL DEFAULT 0,
  amount_received NUMERIC NOT NULL DEFAULT 0,
  amount_returned NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- pos_purchases
CREATE TABLE public.pos_purchases (
  id SERIAL PRIMARY KEY,
  product_id INTEGER REFERENCES public.pos_products(id),
  quantity INTEGER NOT NULL DEFAULT 0,
  unit_cost NUMERIC NOT NULL DEFAULT 0,
  total_cost NUMERIC NOT NULL DEFAULT 0,
  supplier TEXT,
  notes TEXT,
  purchase_date TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- pos_purchase_orders
CREATE TABLE public.pos_purchase_orders (
  id SERIAL PRIMARY KEY,
  purchase_number TEXT UNIQUE,
  supplier TEXT,
  status TEXT NOT NULL DEFAULT 'draft',
  total_amount NUMERIC NOT NULL DEFAULT 0,
  notes TEXT,
  ordered_at TIMESTAMPTZ,
  received_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- pos_purchase_order_items
CREATE TABLE public.pos_purchase_order_items (
  id SERIAL PRIMARY KEY,
  purchase_order_id INTEGER NOT NULL REFERENCES public.pos_purchase_orders(id),
  product_id INTEGER NOT NULL REFERENCES public.pos_products(id),
  quantity INTEGER NOT NULL DEFAULT 0,
  unit_cost NUMERIC NOT NULL DEFAULT 0,
  total_cost NUMERIC NOT NULL DEFAULT 0,
  received_quantity INTEGER DEFAULT 0
);

-- pos_stock_movements
CREATE TABLE public.pos_stock_movements (
  id SERIAL PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES public.pos_products(id),
  movement_type TEXT NOT NULL
    CHECK (movement_type IN ('entry', 'sale', 'adjustment', 'return')),
  quantity INTEGER NOT NULL DEFAULT 0,
  reference_id INTEGER,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- pos_expenses
CREATE TABLE public.pos_expenses (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES public.pos_cash_register_sessions(id),
  description TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  category TEXT,
  beneficiaire TEXT,
  expense_type_id INTEGER REFERENCES public.expense_types(id),
  employee_name TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 4. VIEWS
-- ============================================================

CREATE OR REPLACE VIEW public.slot_availability AS
SELECT 
  t.id AS terrain_id,
  t.code AS terrain_code,
  ts.id AS time_slot_id,
  ts.start_time,
  ts.end_time,
  ts.price,
  r.reservation_date,
  CASE
    WHEN (r.id IS NOT NULL AND r.status = ANY (ARRAY['CONFIRMED'::reservation_status, 'PENDING'::reservation_status]))
    THEN true
    ELSE false
  END AS is_reserved,
  r.id AS reservation_id,
  r.user_id AS reserved_by
FROM terrains t
CROSS JOIN time_slots ts
LEFT JOIN reservations r 
  ON r.terrain_id = t.id 
  AND r.time_slot_id = ts.id 
  AND r.status = ANY (ARRAY['CONFIRMED'::reservation_status, 'PENDING'::reservation_status])
WHERE t.is_active = true AND ts.is_active = true;

-- ============================================================
-- 5. FUNCTIONS
-- ============================================================

-- is_gerant()
CREATE OR REPLACE FUNCTION public.is_gerant()
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'GERANT'
  );
$$;

-- update_updated_at_column()
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- update_coaches_updated_at()
CREATE OR REPLACE FUNCTION public.update_coaches_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- update_events_updated_at()
CREATE OR REPLACE FUNCTION public.update_events_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- update_user_gamification_updated_at()
CREATE OR REPLACE FUNCTION public.update_user_gamification_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- hash_employee_password()
CREATE OR REPLACE FUNCTION public.hash_employee_password()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF NEW.password_hash IS NOT NULL 
     AND NEW.password_hash != '' 
     AND NEW.password_hash NOT LIKE '$2a$%' 
     AND NEW.password_hash NOT LIKE '$2b$%' THEN
    NEW.password_hash := crypt(NEW.password_hash, gen_salt('bf'));
  END IF;
  RETURN NEW;
END;
$$;

-- send_otp()
CREATE OR REPLACE FUNCTION public.send_otp(p_email text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_code text;
  v_expires_at timestamptz;
BEGIN
  v_code := lpad(floor(random() * 10000)::text, 4, '0');
  v_expires_at := now() + interval '10 minutes';
  
  UPDATE public.otp_codes 
  SET expires_at = now() 
  WHERE email = lower(p_email) 
    AND verified = false 
    AND expires_at > now();
  
  INSERT INTO public.otp_codes (email, code, expires_at)
  VALUES (lower(p_email), v_code, v_expires_at);
  
  RETURN json_build_object(
    'success', true,
    'message', 'Code envoyé à ' || p_email,
    'expires_in_seconds', 600
  );
END;
$$;

-- verify_otp()
CREATE OR REPLACE FUNCTION public.verify_otp(p_email text, p_code text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_otp_record record;
  v_user_id uuid;
  v_is_new_user boolean := false;
BEGIN
  SELECT * INTO v_otp_record
  FROM public.otp_codes
  WHERE email = lower(p_email)
    AND verified = false
    AND expires_at > now()
  ORDER BY created_at DESC
  LIMIT 1;
  
  IF v_otp_record IS NULL THEN
    RETURN json_build_object(
      'success', false,
      'error', 'CODE_EXPIRED',
      'message', 'Code expiré ou invalide. Veuillez demander un nouveau code.'
    );
  END IF;
  
  IF v_otp_record.attempts >= 5 THEN
    UPDATE public.otp_codes SET expires_at = now() WHERE id = v_otp_record.id;
    RETURN json_build_object(
      'success', false,
      'error', 'TOO_MANY_ATTEMPTS',
      'message', 'Trop de tentatives. Veuillez demander un nouveau code.'
    );
  END IF;
  
  UPDATE public.otp_codes 
  SET attempts = attempts + 1 
  WHERE id = v_otp_record.id;
  
  IF v_otp_record.code != p_code THEN
    RETURN json_build_object(
      'success', false,
      'error', 'INVALID_CODE',
      'message', 'Code incorrect. ' || (4 - v_otp_record.attempts) || ' tentatives restantes.',
      'attempts_remaining', 4 - v_otp_record.attempts
    );
  END IF;
  
  UPDATE public.otp_codes 
  SET verified = true 
  WHERE id = v_otp_record.id;
  
  SELECT id INTO v_user_id
  FROM auth.users
  WHERE email = lower(p_email)
  LIMIT 1;
  
  IF v_user_id IS NULL THEN
    v_is_new_user := true;
  END IF;
  
  RETURN json_build_object(
    'success', true,
    'message', 'Code vérifié avec succès',
    'is_new_user', v_is_new_user,
    'user_id', v_user_id
  );
END;
$$;

-- get_available_slots()
CREATE OR REPLACE FUNCTION public.get_available_slots(p_date date)
RETURNS TABLE(
  terrain_id bigint, 
  terrain_code text, 
  time_slot_id bigint, 
  start_time time, 
  end_time time, 
  price integer, 
  is_reserved boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    t.id as terrain_id,
    t.code as terrain_code,
    ts.id as time_slot_id,
    ts.start_time,
    ts.end_time,
    ts.price,
    EXISTS (
      SELECT 1 FROM public.reservations r
      WHERE r.terrain_id = t.id 
        AND r.time_slot_id = ts.id
        AND r.reservation_date = p_date
        AND r.status IN ('CONFIRMED', 'PENDING', 'PAID')
    ) as is_reserved
  FROM public.terrains t
  CROSS JOIN public.time_slots ts
  WHERE t.is_active = true AND ts.is_active = true
  ORDER BY ts.start_time, t.code;
END;
$$;

-- calculate_reservation_points()
CREATE OR REPLACE FUNCTION public.calculate_reservation_points(p_time_slot_id bigint)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  v_start_time TIME;
  v_end_time TIME;
  v_duration_minutes INTEGER;
BEGIN
  SELECT start_time, end_time INTO v_start_time, v_end_time
  FROM time_slots WHERE id = p_time_slot_id;
  
  IF v_start_time IS NULL THEN
    RETURN 0;
  END IF;
  
  v_duration_minutes := EXTRACT(EPOCH FROM (v_end_time - v_start_time)) / 60;
  
  IF v_duration_minutes >= 90 THEN
    RETURN 2;
  ELSE
    RETURN 1;
  END IF;
END;
$$;

-- add_reservation_points()
CREATE OR REPLACE FUNCTION public.add_reservation_points(p_reservation_id bigint)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_user_id UUID;
  v_time_slot_id BIGINT;
  v_points INTEGER;
  v_new_total INTEGER;
BEGIN
  SELECT user_id, time_slot_id INTO v_user_id, v_time_slot_id
  FROM reservations WHERE id = p_reservation_id;
  
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Reservation not found');
  END IF;
  
  v_points := calculate_reservation_points(v_time_slot_id);
  
  UPDATE profiles 
  SET points = COALESCE(points, 0) + v_points
  WHERE id = v_user_id
  RETURNING points INTO v_new_total;
  
  RETURN json_build_object(
    'success', true,
    'points_earned', v_points,
    'total_points', v_new_total
  );
END;
$$;

-- get_user_points()
CREATE OR REPLACE FUNCTION public.get_user_points()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_points INTEGER;
BEGIN
  SELECT COALESCE(points, 0) INTO v_points
  FROM profiles WHERE id = auth.uid();
  
  RETURN json_build_object('points', COALESCE(v_points, 0));
END;
$$;

-- employee_has_permission()
CREATE OR REPLACE FUNCTION public.employee_has_permission(p_employee_id uuid, p_permission text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM employees e
    JOIN profile_permissions pp ON pp.profile_id = e.profile_id
    WHERE e.id = p_employee_id
      AND pp.permission_id = p_permission
      AND e.is_active = TRUE
  );
END;
$$;

-- verify_employee_password()
CREATE OR REPLACE FUNCTION public.verify_employee_password(p_username varchar, p_password varchar)
RETURNS TABLE(id uuid, username varchar, full_name varchar, role varchar, is_active boolean)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    e.id,
    e.username,
    e.full_name,
    e.role,
    e.is_active
  FROM public.employees e
  WHERE e.username = p_username
    AND e.password_hash = crypt(p_password, e.password_hash)
    AND e.is_active = true;
  
  UPDATE public.employees 
  SET last_login_at = NOW() 
  WHERE employees.username = p_username 
    AND employees.password_hash = crypt(p_password, employees.password_hash);
END;
$$;

-- verify_employee_password_v2()
CREATE OR REPLACE FUNCTION public.verify_employee_password_v2(p_username text, p_password text)
RETURNS TABLE(
  id uuid, username text, full_name text, role text, is_active boolean,
  profile_id uuid, profile_name text, profile_display_name text,
  base_route text, hierarchy_level integer, permissions text[]
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    e.id,
    e.username::TEXT,
    e.full_name::TEXT,
    e.role::TEXT,
    e.is_active,
    e.profile_id,
    p.name::TEXT AS profile_name,
    p.display_name::TEXT AS profile_display_name,
    p.base_route::TEXT,
    p.hierarchy_level,
    COALESCE(
      ARRAY(
        SELECT pp.permission_id::TEXT
        FROM profile_permissions pp
        WHERE pp.profile_id = e.profile_id
        ORDER BY pp.permission_id
      ),
      ARRAY[]::TEXT[]
    ) AS permissions
  FROM employees e
  LEFT JOIN employee_profiles p ON p.id = e.profile_id
  WHERE e.username = p_username
    AND e.password_hash = crypt(p_password, e.password_hash)
    AND e.is_active = TRUE;
END;
$$;

-- verify_employee_login()
CREATE OR REPLACE FUNCTION public.verify_employee_login(p_username text, p_password text)
RETURNS TABLE(
  id uuid, username text, full_name text, role text, is_active boolean,
  profile_id uuid, profile_name text, profile_display_name text,
  base_route text, hierarchy_level integer, permissions text[]
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    e.id,
    e.username::TEXT,
    e.full_name::TEXT,
    e.role::TEXT,
    e.is_active,
    e.profile_id,
    p.name::TEXT AS profile_name,
    p.display_name::TEXT AS profile_display_name,
    p.base_route::TEXT,
    p.hierarchy_level,
    COALESCE(
      ARRAY(
        SELECT pp.permission_id::TEXT
        FROM profile_permissions pp
        WHERE pp.profile_id = e.profile_id
        ORDER BY pp.permission_id
      ),
      ARRAY[]::TEXT[]
    ) AS permissions
  FROM employees e
  LEFT JOIN employee_profiles p ON p.id = e.profile_id
  WHERE e.username = p_username
    AND e.password_hash = crypt(p_password, e.password_hash)
    AND e.is_active = TRUE;
END;
$$;

-- ============================================================
-- 6. TRIGGERS
-- ============================================================

CREATE TRIGGER reservations_updated_at
  BEFORE UPDATE ON public.reservations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER coaches_updated_at_trigger
  BEFORE UPDATE ON public.coaches
  FOR EACH ROW EXECUTE FUNCTION update_coaches_updated_at();

CREATE TRIGGER events_updated_at
  BEFORE UPDATE ON public.events
  FOR EACH ROW EXECUTE FUNCTION update_events_updated_at();

CREATE TRIGGER trg_hash_employee_password
  BEFORE INSERT OR UPDATE ON public.employees
  FOR EACH ROW EXECUTE FUNCTION hash_employee_password();

-- ============================================================
-- 7. ROW LEVEL SECURITY (RLS)
-- ============================================================

-- Enable RLS on tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.terrains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otp_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coaches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservation_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reclamations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_cash_register_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_expenses ENABLE ROW LEVEL SECURITY;

-- NOTE: These tables have RLS DISABLED:
-- ALTER TABLE public.reservations DISABLE ROW LEVEL SECURITY;  -- RLS disabled
-- ALTER TABLE public.clients DISABLE ROW LEVEL SECURITY;       -- RLS disabled
-- ALTER TABLE public.app_settings DISABLE ROW LEVEL SECURITY;  -- RLS disabled
-- ALTER TABLE public.pos_order_payments DISABLE ROW LEVEL SECURITY; -- RLS disabled

-- ============================================================
-- RLS POLICIES
-- ============================================================

-- profiles
CREATE POLICY "Profiles: user can read own" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Profiles: user can insert own" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Profiles: user can update own" ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Profiles: gerant can read all" ON public.profiles FOR SELECT USING (is_gerant());
CREATE POLICY "Profiles: gerant can update all" ON public.profiles FOR UPDATE USING (is_gerant()) WITH CHECK (is_gerant());
CREATE POLICY "Backoffice: can read all profiles" ON public.profiles FOR SELECT TO public USING (true);

-- terrains
CREATE POLICY "Terrains: public read" ON public.terrains FOR SELECT TO public USING (true);
CREATE POLICY "Public read access" ON public.terrains FOR SELECT TO public USING (true);
CREATE POLICY "Terrains: gerant write" ON public.terrains FOR ALL TO public
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'GERANT'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'GERANT'));

-- time_slots
CREATE POLICY "Public read access" ON public.time_slots FOR SELECT TO public USING (true);
CREATE POLICY "time_slots_select_anon" ON public.time_slots FOR SELECT TO anon USING (true);
CREATE POLICY "time_slots_select_authenticated" ON public.time_slots FOR SELECT TO authenticated USING (true);

-- coaches
CREATE POLICY "Anyone can view active coaches" ON public.coaches FOR SELECT TO public USING (is_active = true);
CREATE POLICY "Authenticated users can view all coaches" ON public.coaches FOR SELECT TO authenticated USING (true);
CREATE POLICY "Service role can manage coaches" ON public.coaches FOR ALL TO service_role USING (true) WITH CHECK (true);

-- employees
CREATE POLICY "Allow read for authenticated" ON public.employees FOR SELECT TO public USING (true);
CREATE POLICY "Backoffice: can read employees" ON public.employees FOR SELECT TO public USING (true);
CREATE POLICY "Backoffice: can insert employees" ON public.employees FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Backoffice: can update employees" ON public.employees FOR UPDATE TO public USING (true);
CREATE POLICY "Backoffice: can delete employees" ON public.employees FOR DELETE TO public USING (true);

-- employee_profiles
CREATE POLICY "Allow public read on employee_profiles" ON public.employee_profiles FOR SELECT TO public USING (true);
CREATE POLICY "Allow anon full access on employee_profiles" ON public.employee_profiles FOR ALL TO public USING (true) WITH CHECK (true);

-- permissions
CREATE POLICY "Allow public read on permissions" ON public.permissions FOR SELECT TO public USING (true);
CREATE POLICY "Allow anon full access on permissions" ON public.permissions FOR ALL TO public USING (true) WITH CHECK (true);

-- profile_permissions
CREATE POLICY "Allow public read on profile_permissions" ON public.profile_permissions FOR SELECT TO public USING (true);
CREATE POLICY "Allow anon full access on profile_permissions" ON public.profile_permissions FOR ALL TO public USING (true) WITH CHECK (true);

-- payment_methods
CREATE POLICY "Allow public read" ON public.payment_methods FOR SELECT TO anon USING (true);
CREATE POLICY "Allow authenticated read" ON public.payment_methods FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated manage" ON public.payment_methods FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- reservation_payments
CREATE POLICY "Allow authenticated read" ON public.reservation_payments FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated manage" ON public.reservation_payments FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- reclamations
CREATE POLICY "Users can view own reclamations" ON public.reclamations FOR SELECT TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can create reclamations" ON public.reclamations FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own pending reclamations" ON public.reclamations FOR UPDATE TO public USING (auth.uid() = user_id AND status::text = 'pending');

-- expense_types
CREATE POLICY "Backoffice: can read expense_types" ON public.expense_types FOR SELECT TO public USING (true);
CREATE POLICY "Backoffice: can manage expense_types" ON public.expense_types FOR ALL TO public USING (true);

-- expenses
CREATE POLICY "Backoffice: can read expenses" ON public.expenses FOR SELECT TO public USING (true);
CREATE POLICY "Backoffice: can insert expenses" ON public.expenses FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Backoffice: can update expenses" ON public.expenses FOR UPDATE TO public USING (true);
CREATE POLICY "Backoffice: can delete expenses" ON public.expenses FOR DELETE TO public USING (true);

-- events
CREATE POLICY "Published events are viewable by everyone" ON public.events FOR SELECT TO public USING (status = 'PUBLISHED'::event_status);
CREATE POLICY "Managers can manage events" ON public.events FOR ALL TO public
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'::user_role))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'::user_role));

-- event_images
CREATE POLICY "Event images are viewable for published events" ON public.event_images FOR SELECT TO public
  USING (EXISTS (SELECT 1 FROM events WHERE events.id = event_images.event_id AND events.status = 'PUBLISHED'::event_status));
CREATE POLICY "Managers can manage event images" ON public.event_images FOR ALL TO public
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'::user_role))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'::user_role));

-- POS policies (all allow public/anon full access)
CREATE POLICY "Allow all for anon" ON public.pos_categories FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_products FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated" ON public.pos_tables FOR ALL TO public USING (true);
CREATE POLICY "Allow all for anon" ON public.pos_cash_register_sessions FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_orders FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_order_items FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_purchases FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_purchase_orders FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_purchase_order_items FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_stock_movements FOR ALL TO public USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated" ON public.pos_expenses FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- 8. STORAGE BUCKETS
-- ============================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES 
  ('avatars', 'avatars', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']),
  ('event-images', 'event-images', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif']),
  ('reclamations', 'reclamations', false, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp']);

-- ============================================================
-- END OF SCHEMA
-- ============================================================
