-- ============================================================================
-- PADELHOUSE - Export Complet Base de Données
-- Source: qxauriiupckwouucmgkr (PadelHouse, eu-central-1)
-- Date: 2026-03-18
-- 
-- IMPORTANT: Après import, remplacer 'qxauriiupckwouucmgkr' par le nouveau
-- project_id dans les fonctions notify_event_published et 
-- notify_reservation_confirmed.
-- ============================================================================

-- ============================================================================
-- 1. EXTENSIONS
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;

-- ============================================================================
-- 2. ENUMS
-- ============================================================================
DO $$ BEGIN
  CREATE TYPE public.user_role AS ENUM ('JOUEUR', 'GERANT', 'EMPLOYE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.reservation_status AS ENUM ('PENDING', 'CONFIRMED', 'CANCELED', 'EXPIRED', 'PAID');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.event_status AS ENUM ('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TYPE public.event_category AS ENUM ('TOURNOI', 'FORMATION', 'SOCIAL', 'ANIMATION', 'COMPETITION', 'AUTRE');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- 3. TABLES (sans FK - ajoutées séparément à la fin)
-- ============================================================================

-- ---------- terrains ----------
CREATE TABLE IF NOT EXISTS public.terrains (
  id bigint NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.terrains', 'id')),
  code text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT terrains_pkey PRIMARY KEY (id),
  CONSTRAINT terrains_code_key UNIQUE (code)
);
-- Créer la séquence si la table est nouvelle
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'terrains_id_seq') THEN
    CREATE SEQUENCE public.terrains_id_seq OWNED BY public.terrains.id;
    ALTER TABLE public.terrains ALTER COLUMN id SET DEFAULT nextval('public.terrains_id_seq'::regclass);
  END IF;
END $$;

-- ---------- time_slots ----------
CREATE TABLE IF NOT EXISTS public.time_slots (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  start_time time NOT NULL,
  end_time time NOT NULL,
  price integer NOT NULL DEFAULT 10000,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT time_slots_pkey PRIMARY KEY (id),
  CONSTRAINT time_slots_unique UNIQUE (start_time, end_time)
);

-- ---------- permissions ----------
CREATE TABLE IF NOT EXISTS public.permissions (
  id varchar(50) NOT NULL,
  display_name varchar(100) NOT NULL,
  description text,
  category varchar(50) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);

-- ---------- employee_profiles ----------
CREATE TABLE IF NOT EXISTS public.employee_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name varchar(50) NOT NULL,
  display_name varchar(100) NOT NULL,
  description text,
  base_route varchar(100) NOT NULL DEFAULT '/',
  hierarchy_level integer NOT NULL DEFAULT 10,
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT employee_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT employee_profiles_name_key UNIQUE (name)
);

-- ---------- coaches ----------
CREATE TABLE IF NOT EXISTS public.coaches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  first_name text NOT NULL,
  last_name text NOT NULL,
  phone text NOT NULL,
  image_url text,
  bio text,
  is_active boolean DEFAULT true,
  price_1h_solo integer NOT NULL DEFAULT 0,
  price_1h30_solo integer NOT NULL DEFAULT 0,
  price_1h_duo integer NOT NULL DEFAULT 0,
  price_1h30_duo integer NOT NULL DEFAULT 0,
  price_1h_trio integer NOT NULL DEFAULT 0,
  price_1h30_trio integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT coaches_pkey PRIMARY KEY (id)
);

-- ---------- payment_methods ----------
CREATE TABLE IF NOT EXISTS public.payment_methods (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.payment_methods', 'id')),
  name text NOT NULL,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT payment_methods_name_key UNIQUE (name)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'payment_methods_id_seq') THEN
    CREATE SEQUENCE public.payment_methods_id_seq OWNED BY public.payment_methods.id;
    ALTER TABLE public.payment_methods ALTER COLUMN id SET DEFAULT nextval('public.payment_methods_id_seq'::regclass);
  END IF;
END $$;

-- ---------- expense_types ----------
CREATE TABLE IF NOT EXISTS public.expense_types (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.expense_types', 'id')),
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT expense_types_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'expense_types_id_seq') THEN
    CREATE SEQUENCE public.expense_types_id_seq OWNED BY public.expense_types.id;
    ALTER TABLE public.expense_types ALTER COLUMN id SET DEFAULT nextval('public.expense_types_id_seq'::regclass);
  END IF;
END $$;

-- ---------- clients ----------
CREATE TABLE IF NOT EXISTS public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  phone text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_phone_key UNIQUE (phone)
);

-- ---------- otp_codes ----------
CREATE TABLE IF NOT EXISTS public.otp_codes (
  id bigint NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.otp_codes', 'id')),
  email text NOT NULL,
  code text NOT NULL,
  expires_at timestamptz NOT NULL,
  verified boolean NOT NULL DEFAULT false,
  attempts integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT otp_codes_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'otp_codes_id_seq') THEN
    CREATE SEQUENCE public.otp_codes_id_seq OWNED BY public.otp_codes.id;
    ALTER TABLE public.otp_codes ALTER COLUMN id SET DEFAULT nextval('public.otp_codes_id_seq'::regclass);
  END IF;
END $$;

-- ---------- notification_logs ----------
CREATE TABLE IF NOT EXISTS public.notification_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  type text NOT NULL CHECK (type = ANY (ARRAY['reservation_confirmed', 'reservation_reminder', 'event_published', 'custom'])),
  title text NOT NULL,
  body text NOT NULL,
  data jsonb DEFAULT '{}'::jsonb,
  target_type text NOT NULL DEFAULT 'all' CHECK (target_type = ANY (ARRAY['single', 'multiple', 'all'])),
  target_user_ids uuid[] DEFAULT '{}'::uuid[],
  total_sent integer NOT NULL DEFAULT 0,
  total_failed integer NOT NULL DEFAULT 0,
  sent_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notification_logs_pkey PRIMARY KEY (id)
);

-- ---------- packages ----------
CREATE TABLE IF NOT EXISTS public.packages (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.packages', 'id')),
  name text NOT NULL,
  description text,
  total_sessions integer NOT NULL CHECK (total_sessions > 0),
  price integer NOT NULL CHECK (price >= 0),
  regular_price integer NOT NULL CHECK (regular_price >= 0),
  duration_minutes integer NOT NULL DEFAULT 60,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT packages_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'packages_id_seq') THEN
    CREATE SEQUENCE public.packages_id_seq OWNED BY public.packages.id;
    ALTER TABLE public.packages ALTER COLUMN id SET DEFAULT nextval('public.packages_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_categories ----------
CREATE TABLE IF NOT EXISTS public.pos_categories (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_categories', 'id')),
  name text NOT NULL,
  icon text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT pos_categories_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_categories_id_seq') THEN
    CREATE SEQUENCE public.pos_categories_id_seq OWNED BY public.pos_categories.id;
    ALTER TABLE public.pos_categories ALTER COLUMN id SET DEFAULT nextval('public.pos_categories_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_tables ----------
CREATE TABLE IF NOT EXISTS public.pos_tables (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_tables', 'id')),
  name text NOT NULL,
  capacity integer NOT NULL DEFAULT 2,
  position_x integer NOT NULL DEFAULT 0,
  position_y integer NOT NULL DEFAULT 0,
  shape text NOT NULL DEFAULT 'round',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT pos_tables_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_tables_id_seq') THEN
    CREATE SEQUENCE public.pos_tables_id_seq OWNED BY public.pos_tables.id;
    ALTER TABLE public.pos_tables ALTER COLUMN id SET DEFAULT nextval('public.pos_tables_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_cash_register_sessions ----------
CREATE TABLE IF NOT EXISTS public.pos_cash_register_sessions (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_cash_register_sessions', 'id')),
  opened_by text NOT NULL,
  closed_by text,
  opening_amount integer NOT NULL DEFAULT 0,
  closing_amount integer,
  expected_amount integer,
  notes text,
  opened_at timestamptz DEFAULT now(),
  closed_at timestamptz,
  CONSTRAINT pos_cash_register_sessions_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_cash_register_sessions_id_seq') THEN
    CREATE SEQUENCE public.pos_cash_register_sessions_id_seq OWNED BY public.pos_cash_register_sessions.id;
    ALTER TABLE public.pos_cash_register_sessions ALTER COLUMN id SET DEFAULT nextval('public.pos_cash_register_sessions_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_purchase_orders ----------
CREATE TABLE IF NOT EXISTS public.pos_purchase_orders (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_purchase_orders', 'id')),
  purchase_number text NOT NULL,
  supplier text,
  notes text,
  total_cost integer NOT NULL DEFAULT 0,
  item_count integer NOT NULL DEFAULT 0,
  purchase_date date NOT NULL DEFAULT CURRENT_DATE,
  created_by text NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT pos_purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT pos_purchase_orders_purchase_number_key UNIQUE (purchase_number)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_purchase_orders_id_seq') THEN
    CREATE SEQUENCE public.pos_purchase_orders_id_seq OWNED BY public.pos_purchase_orders.id;
    ALTER TABLE public.pos_purchase_orders ALTER COLUMN id SET DEFAULT nextval('public.pos_purchase_orders_id_seq'::regclass);
  END IF;
END $$;

-- ---------- profiles ----------
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid NOT NULL,
  email text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  birth_date date NOT NULL,
  gender text,
  role user_role NOT NULL DEFAULT 'JOUEUR',
  created_at timestamptz NOT NULL DEFAULT now(),
  phone text,
  points integer DEFAULT 0,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_email_key UNIQUE (email)
);

-- ---------- employees ----------
CREATE TABLE IF NOT EXISTS public.employees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  username varchar(50) NOT NULL,
  password_hash text NOT NULL,
  full_name varchar(100),
  role varchar(20) DEFAULT 'admin',
  is_active boolean DEFAULT true,
  last_login_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  profile_id uuid,
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_username_key UNIQUE (username)
);

-- ---------- profile_permissions ----------
CREATE TABLE IF NOT EXISTS public.profile_permissions (
  profile_id uuid NOT NULL,
  permission_id varchar(50) NOT NULL,
  CONSTRAINT profile_permissions_pkey PRIMARY KEY (profile_id, permission_id)
);

-- ---------- app_settings ----------
CREATE TABLE IF NOT EXISTS public.app_settings (
  id integer NOT NULL DEFAULT 1,
  business_name text DEFAULT 'Padel House',
  business_phone text,
  business_email text,
  business_address text,
  opening_time time DEFAULT '08:00:00',
  closing_time time DEFAULT '23:00:00',
  min_advance_booking integer DEFAULT 1,
  max_advance_booking integer DEFAULT 14,
  cancellation_deadline integer DEFAULT 24,
  currency text DEFAULT 'FCFA',
  notifications_enabled boolean DEFAULT true,
  email_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  manual_reservation_user_id uuid,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  security_code text DEFAULT '0451373',
  default_tax_rate numeric(5,2) NOT NULL DEFAULT 0,
  otp_security_code text DEFAULT '045137',
  CONSTRAINT app_settings_pkey PRIMARY KEY (id),
  CONSTRAINT single_row CHECK (id = 1)
);

-- ---------- fcm_tokens ----------
CREATE TABLE IF NOT EXISTS public.fcm_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL,
  token text NOT NULL,
  device_type text NOT NULL DEFAULT 'android' CHECK (device_type = ANY (ARRAY['android', 'ios', 'web'])),
  device_name text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fcm_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT fcm_tokens_user_id_token_key UNIQUE (user_id, token)
);

-- ---------- events ----------
CREATE TABLE IF NOT EXISTS public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  subtitle text,
  description text NOT NULL,
  long_description text,
  category event_category NOT NULL DEFAULT 'AUTRE',
  status event_status NOT NULL DEFAULT 'DRAFT',
  start_date timestamptz NOT NULL,
  end_date timestamptz,
  location text NOT NULL DEFAULT 'PadelHouse Club',
  cover_image_url text,
  is_featured boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 0,
  tags text[] DEFAULT '{}'::text[],
  price_info text,
  is_free boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  contact_phone text DEFAULT '+2250799998888',
  CONSTRAINT events_pkey PRIMARY KEY (id)
);

-- ---------- event_images ----------
CREATE TABLE IF NOT EXISTS public.event_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL,
  image_url text NOT NULL,
  caption text,
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT event_images_pkey PRIMARY KEY (id)
);

-- ---------- reservations ----------
CREATE TABLE IF NOT EXISTS public.reservations (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  terrain_id bigint NOT NULL,
  time_slot_id bigint NOT NULL,
  reservation_date date NOT NULL,
  user_id uuid NOT NULL,
  status reservation_status NOT NULL DEFAULT 'CONFIRMED',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  client_id uuid,
  CONSTRAINT reservations_pkey PRIMARY KEY (id)
);

-- ---------- reservation_payments ----------
CREATE TABLE IF NOT EXISTS public.reservation_payments (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.reservation_payments', 'id')),
  reservation_id integer NOT NULL,
  payment_method_id integer NOT NULL,
  amount numeric(10,2) NOT NULL,
  created_at timestamptz DEFAULT now(),
  amount_received numeric(10,2) DEFAULT 0,
  amount_returned numeric(10,2) DEFAULT 0,
  CONSTRAINT reservation_payments_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'reservation_payments_id_seq') THEN
    CREATE SEQUENCE public.reservation_payments_id_seq OWNED BY public.reservation_payments.id;
    ALTER TABLE public.reservation_payments ALTER COLUMN id SET DEFAULT nextval('public.reservation_payments_id_seq'::regclass);
  END IF;
END $$;

-- ---------- client_packages ----------
CREATE TABLE IF NOT EXISTS public.client_packages (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.client_packages', 'id')),
  package_id integer NOT NULL,
  user_id uuid NOT NULL,
  sessions_total integer NOT NULL CHECK (sessions_total > 0),
  sessions_used integer NOT NULL DEFAULT 0 CHECK (sessions_used >= 0),
  paid_amount integer NOT NULL DEFAULT 0,
  payment_method text CHECK (payment_method = ANY (ARRAY['cash', 'card', 'transfer', 'mixed'])),
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status = ANY (ARRAY['ACTIVE', 'COMPLETED', 'EXPIRED', 'CANCELLED'])),
  notes text,
  assigned_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  CONSTRAINT client_packages_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'client_packages_id_seq') THEN
    CREATE SEQUENCE public.client_packages_id_seq OWNED BY public.client_packages.id;
    ALTER TABLE public.client_packages ALTER COLUMN id SET DEFAULT nextval('public.client_packages_id_seq'::regclass);
  END IF;
END $$;

-- ---------- client_package_sessions ----------
CREATE TABLE IF NOT EXISTS public.client_package_sessions (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.client_package_sessions', 'id')),
  client_package_id integer NOT NULL,
  reservation_id bigint,
  session_date date NOT NULL,
  terrain_id bigint,
  time_slot_id bigint,
  status text NOT NULL DEFAULT 'USED' CHECK (status = ANY (ARRAY['USED', 'CANCELLED'])),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT client_package_sessions_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'client_package_sessions_id_seq') THEN
    CREATE SEQUENCE public.client_package_sessions_id_seq OWNED BY public.client_package_sessions.id;
    ALTER TABLE public.client_package_sessions ALTER COLUMN id SET DEFAULT nextval('public.client_package_sessions_id_seq'::regclass);
  END IF;
END $$;

-- ---------- package_time_slots ----------
CREATE TABLE IF NOT EXISTS public.package_time_slots (
  package_id integer NOT NULL,
  time_slot_id bigint NOT NULL,
  CONSTRAINT package_time_slots_pkey PRIMARY KEY (package_id, time_slot_id)
);

-- ---------- abonnements ----------
CREATE TABLE IF NOT EXISTS public.abonnements (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.abonnements', 'id')),
  user_id uuid NOT NULL,
  terrain_id integer NOT NULL,
  time_slot_id integer NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_date date NOT NULL,
  end_date date NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE' CHECK (status = ANY (ARRAY['ACTIVE', 'PAUSED', 'EXPIRED', 'CANCELLED'])),
  notes text,
  created_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT abonnements_pkey PRIMARY KEY (id),
  CONSTRAINT abonnements_date_check CHECK (end_date >= start_date)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'abonnements_id_seq') THEN
    CREATE SEQUENCE public.abonnements_id_seq OWNED BY public.abonnements.id;
    ALTER TABLE public.abonnements ALTER COLUMN id SET DEFAULT nextval('public.abonnements_id_seq'::regclass);
  END IF;
END $$;

-- ---------- reclamations ----------
CREATE TABLE IF NOT EXISTS public.reclamations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  subject varchar(255) NOT NULL,
  description text NOT NULL,
  category varchar(50) NOT NULL DEFAULT 'general' CHECK (category::text = ANY (ARRAY['general', 'reservation', 'terrain', 'paiement', 'autre'])),
  status varchar(20) NOT NULL DEFAULT 'pending' CHECK (status::text = ANY (ARRAY['pending', 'in_progress', 'resolved', 'rejected'])),
  photo_urls text[] DEFAULT '{}'::text[],
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  resolved_at timestamptz,
  admin_response text,
  CONSTRAINT reclamations_pkey PRIMARY KEY (id)
);

-- ---------- expenses ----------
CREATE TABLE IF NOT EXISTS public.expenses (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.expenses', 'id')),
  expense_type_id integer NOT NULL,
  description text NOT NULL,
  amount numeric(12,2) NOT NULL DEFAULT 0,
  expense_date date NOT NULL DEFAULT CURRENT_DATE,
  employee_name text,
  beneficiaire text,
  notes text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT expenses_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'expenses_id_seq') THEN
    CREATE SEQUENCE public.expenses_id_seq OWNED BY public.expenses.id;
    ALTER TABLE public.expenses ALTER COLUMN id SET DEFAULT nextval('public.expenses_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_products ----------
CREATE TABLE IF NOT EXISTS public.pos_products (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_products', 'id')),
  name text NOT NULL,
  category_id integer,
  price integer NOT NULL DEFAULT 0,
  stock_quantity integer,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  product_type text NOT NULL DEFAULT 'service',
  purchase_price integer NOT NULL DEFAULT 0,
  selling_price_ht integer NOT NULL DEFAULT 0,
  tax_rate numeric(5,2) NOT NULL DEFAULT 0,
  price_ttc integer NOT NULL DEFAULT 0,
  CONSTRAINT pos_products_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_products_id_seq') THEN
    CREATE SEQUENCE public.pos_products_id_seq OWNED BY public.pos_products.id;
    ALTER TABLE public.pos_products ALTER COLUMN id SET DEFAULT nextval('public.pos_products_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_orders ----------
CREATE TABLE IF NOT EXISTS public.pos_orders (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_orders', 'id')),
  order_number text NOT NULL,
  session_id integer,
  total integer NOT NULL DEFAULT 0,
  payment_method text NOT NULL DEFAULT 'cash',
  cash_received integer,
  change_given integer,
  employee_name text NOT NULL,
  notes text,
  created_at timestamptz DEFAULT now(),
  status text NOT NULL DEFAULT 'completed',
  terrain_id bigint,
  time_slot_id bigint,
  reservation_date date,
  order_type text,
  table_id integer,
  reservation_id bigint,
  client_name text,
  client_phone text,
  payment_status text DEFAULT 'paid',
  CONSTRAINT pos_orders_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_orders_id_seq') THEN
    CREATE SEQUENCE public.pos_orders_id_seq OWNED BY public.pos_orders.id;
    ALTER TABLE public.pos_orders ALTER COLUMN id SET DEFAULT nextval('public.pos_orders_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_order_items ----------
CREATE TABLE IF NOT EXISTS public.pos_order_items (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_order_items', 'id')),
  order_id integer NOT NULL,
  product_id integer,
  product_name text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_price integer NOT NULL DEFAULT 0,
  total integer NOT NULL DEFAULT 0,
  CONSTRAINT pos_order_items_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_order_items_id_seq') THEN
    CREATE SEQUENCE public.pos_order_items_id_seq OWNED BY public.pos_order_items.id;
    ALTER TABLE public.pos_order_items ALTER COLUMN id SET DEFAULT nextval('public.pos_order_items_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_order_payments ----------
CREATE TABLE IF NOT EXISTS public.pos_order_payments (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_order_payments', 'id')),
  order_id integer NOT NULL,
  payment_method_id integer NOT NULL,
  amount numeric(12,2) NOT NULL DEFAULT 0,
  amount_received numeric(12,2) NOT NULL DEFAULT 0,
  amount_returned numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pos_order_payments_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_order_payments_id_seq') THEN
    CREATE SEQUENCE public.pos_order_payments_id_seq OWNED BY public.pos_order_payments.id;
    ALTER TABLE public.pos_order_payments ALTER COLUMN id SET DEFAULT nextval('public.pos_order_payments_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_purchases ----------
CREATE TABLE IF NOT EXISTS public.pos_purchases (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_purchases', 'id')),
  product_id integer NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_cost integer NOT NULL DEFAULT 0,
  total_cost integer NOT NULL DEFAULT 0,
  supplier text,
  reference text,
  notes text,
  purchase_date date NOT NULL DEFAULT CURRENT_DATE,
  created_by text NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT pos_purchases_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_purchases_id_seq') THEN
    CREATE SEQUENCE public.pos_purchases_id_seq OWNED BY public.pos_purchases.id;
    ALTER TABLE public.pos_purchases ALTER COLUMN id SET DEFAULT nextval('public.pos_purchases_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_purchase_order_items ----------
CREATE TABLE IF NOT EXISTS public.pos_purchase_order_items (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_purchase_order_items', 'id')),
  purchase_order_id integer NOT NULL,
  product_id integer NOT NULL,
  product_name text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_cost integer NOT NULL DEFAULT 0,
  total_cost integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT pos_purchase_order_items_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_purchase_order_items_id_seq') THEN
    CREATE SEQUENCE public.pos_purchase_order_items_id_seq OWNED BY public.pos_purchase_order_items.id;
    ALTER TABLE public.pos_purchase_order_items ALTER COLUMN id SET DEFAULT nextval('public.pos_purchase_order_items_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_stock_movements ----------
CREATE TABLE IF NOT EXISTS public.pos_stock_movements (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_stock_movements', 'id')),
  product_id integer NOT NULL,
  product_name text NOT NULL,
  movement_type text NOT NULL,
  quantity integer NOT NULL,
  reference_type text,
  reference_id integer,
  reference_number text,
  note text,
  created_by text NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT pos_stock_movements_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_stock_movements_id_seq') THEN
    CREATE SEQUENCE public.pos_stock_movements_id_seq OWNED BY public.pos_stock_movements.id;
    ALTER TABLE public.pos_stock_movements ALTER COLUMN id SET DEFAULT nextval('public.pos_stock_movements_id_seq'::regclass);
  END IF;
END $$;

-- ---------- pos_expenses ----------
CREATE TABLE IF NOT EXISTS public.pos_expenses (
  id integer NOT NULL DEFAULT nextval(pg_get_serial_sequence('public.pos_expenses', 'id')),
  session_id integer NOT NULL,
  description text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  category text,
  beneficiaire text,
  expense_type_id integer,
  employee_name text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT pos_expenses_pkey PRIMARY KEY (id)
);
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pos_expenses_id_seq') THEN
    CREATE SEQUENCE public.pos_expenses_id_seq OWNED BY public.pos_expenses.id;
    ALTER TABLE public.pos_expenses ALTER COLUMN id SET DEFAULT nextval('public.pos_expenses_id_seq'::regclass);
  END IF;
END $$;

-- ============================================================================
-- 4. FOREIGN KEYS
-- ============================================================================
ALTER TABLE public.profiles ADD CONSTRAINT profiles_id_fkey
  FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.employees ADD CONSTRAINT employees_profile_id_fkey
  FOREIGN KEY (profile_id) REFERENCES public.employee_profiles(id);

ALTER TABLE public.profile_permissions ADD CONSTRAINT profile_permissions_profile_id_fkey
  FOREIGN KEY (profile_id) REFERENCES public.employee_profiles(id) ON DELETE CASCADE;

ALTER TABLE public.profile_permissions ADD CONSTRAINT profile_permissions_permission_id_fkey
  FOREIGN KEY (permission_id) REFERENCES public.permissions(id) ON DELETE CASCADE;

ALTER TABLE public.app_settings ADD CONSTRAINT app_settings_manual_reservation_user_id_fkey
  FOREIGN KEY (manual_reservation_user_id) REFERENCES public.profiles(id);

ALTER TABLE public.fcm_tokens ADD CONSTRAINT fcm_tokens_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE public.events ADD CONSTRAINT events_created_by_fkey
  FOREIGN KEY (created_by) REFERENCES auth.users(id);

ALTER TABLE public.event_images ADD CONSTRAINT event_images_event_id_fkey
  FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE;

ALTER TABLE public.reservations ADD CONSTRAINT reservations_terrain_id_fkey
  FOREIGN KEY (terrain_id) REFERENCES public.terrains(id);

ALTER TABLE public.reservations ADD CONSTRAINT reservations_time_slot_id_fkey
  FOREIGN KEY (time_slot_id) REFERENCES public.time_slots(id);

ALTER TABLE public.reservations ADD CONSTRAINT reservations_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id);

ALTER TABLE public.reservations ADD CONSTRAINT reservations_user_id_profiles_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id);

ALTER TABLE public.reservations ADD CONSTRAINT reservations_client_id_fkey
  FOREIGN KEY (client_id) REFERENCES public.clients(id);

ALTER TABLE public.reservation_payments ADD CONSTRAINT reservation_payments_reservation_id_fkey
  FOREIGN KEY (reservation_id) REFERENCES public.reservations(id);

ALTER TABLE public.reservation_payments ADD CONSTRAINT reservation_payments_payment_method_id_fkey
  FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id);

ALTER TABLE public.client_packages ADD CONSTRAINT client_packages_package_id_fkey
  FOREIGN KEY (package_id) REFERENCES public.packages(id);

ALTER TABLE public.client_packages ADD CONSTRAINT client_packages_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id);

ALTER TABLE public.client_package_sessions ADD CONSTRAINT client_package_sessions_client_package_id_fkey
  FOREIGN KEY (client_package_id) REFERENCES public.client_packages(id);

ALTER TABLE public.client_package_sessions ADD CONSTRAINT client_package_sessions_reservation_id_fkey
  FOREIGN KEY (reservation_id) REFERENCES public.reservations(id);

ALTER TABLE public.client_package_sessions ADD CONSTRAINT client_package_sessions_terrain_id_fkey
  FOREIGN KEY (terrain_id) REFERENCES public.terrains(id);

ALTER TABLE public.client_package_sessions ADD CONSTRAINT client_package_sessions_time_slot_id_fkey
  FOREIGN KEY (time_slot_id) REFERENCES public.time_slots(id);

ALTER TABLE public.package_time_slots ADD CONSTRAINT package_time_slots_package_id_fkey
  FOREIGN KEY (package_id) REFERENCES public.packages(id);

ALTER TABLE public.package_time_slots ADD CONSTRAINT package_time_slots_time_slot_id_fkey
  FOREIGN KEY (time_slot_id) REFERENCES public.time_slots(id);

ALTER TABLE public.abonnements ADD CONSTRAINT abonnements_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES public.profiles(id);

ALTER TABLE public.abonnements ADD CONSTRAINT abonnements_terrain_id_fkey
  FOREIGN KEY (terrain_id) REFERENCES public.terrains(id);

ALTER TABLE public.abonnements ADD CONSTRAINT abonnements_time_slot_id_fkey
  FOREIGN KEY (time_slot_id) REFERENCES public.time_slots(id);

ALTER TABLE public.reclamations ADD CONSTRAINT reclamations_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES auth.users(id);

ALTER TABLE public.expenses ADD CONSTRAINT expenses_expense_type_id_fkey
  FOREIGN KEY (expense_type_id) REFERENCES public.expense_types(id);

ALTER TABLE public.pos_products ADD CONSTRAINT pos_products_category_id_fkey
  FOREIGN KEY (category_id) REFERENCES public.pos_categories(id);

ALTER TABLE public.pos_orders ADD CONSTRAINT pos_orders_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.pos_cash_register_sessions(id);

ALTER TABLE public.pos_orders ADD CONSTRAINT pos_orders_terrain_id_fkey
  FOREIGN KEY (terrain_id) REFERENCES public.terrains(id);

ALTER TABLE public.pos_orders ADD CONSTRAINT pos_orders_time_slot_id_fkey
  FOREIGN KEY (time_slot_id) REFERENCES public.time_slots(id);

ALTER TABLE public.pos_orders ADD CONSTRAINT pos_orders_reservation_id_fkey
  FOREIGN KEY (reservation_id) REFERENCES public.reservations(id);

ALTER TABLE public.pos_orders ADD CONSTRAINT pos_orders_table_id_fkey
  FOREIGN KEY (table_id) REFERENCES public.pos_tables(id);

ALTER TABLE public.pos_order_items ADD CONSTRAINT pos_order_items_order_id_fkey
  FOREIGN KEY (order_id) REFERENCES public.pos_orders(id) ON DELETE CASCADE;

ALTER TABLE public.pos_order_items ADD CONSTRAINT pos_order_items_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES public.pos_products(id);

ALTER TABLE public.pos_order_payments ADD CONSTRAINT pos_order_payments_order_id_fkey
  FOREIGN KEY (order_id) REFERENCES public.pos_orders(id) ON DELETE CASCADE;

ALTER TABLE public.pos_order_payments ADD CONSTRAINT pos_order_payments_payment_method_id_fkey
  FOREIGN KEY (payment_method_id) REFERENCES public.payment_methods(id);

ALTER TABLE public.pos_purchases ADD CONSTRAINT pos_purchases_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES public.pos_products(id);

ALTER TABLE public.pos_purchase_order_items ADD CONSTRAINT pos_purchase_order_items_purchase_order_id_fkey
  FOREIGN KEY (purchase_order_id) REFERENCES public.pos_purchase_orders(id) ON DELETE CASCADE;

ALTER TABLE public.pos_purchase_order_items ADD CONSTRAINT pos_purchase_order_items_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES public.pos_products(id);

ALTER TABLE public.pos_stock_movements ADD CONSTRAINT pos_stock_movements_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES public.pos_products(id);

ALTER TABLE public.pos_expenses ADD CONSTRAINT pos_expenses_session_id_fkey
  FOREIGN KEY (session_id) REFERENCES public.pos_cash_register_sessions(id);

ALTER TABLE public.pos_expenses ADD CONSTRAINT pos_expenses_expense_type_id_fkey
  FOREIGN KEY (expense_type_id) REFERENCES public.expense_types(id);

-- ============================================================================
-- 5. INDEX
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_coaches_is_active ON public.coaches USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_employees_username ON public.employees USING btree (username);
CREATE INDEX IF NOT EXISTS idx_clients_phone ON public.clients USING btree (phone);
CREATE INDEX IF NOT EXISTS idx_otp_codes_email ON public.otp_codes USING btree (email);
CREATE INDEX IF NOT EXISTS idx_otp_codes_expires ON public.otp_codes USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_notification_logs_type ON public.notification_logs USING btree (type);
CREATE INDEX IF NOT EXISTS idx_notification_logs_created ON public.notification_logs USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_fcm_tokens_user_id ON public.fcm_tokens USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_fcm_tokens_active ON public.fcm_tokens USING btree (is_active) WHERE (is_active = true);
CREATE INDEX IF NOT EXISTS idx_events_status ON public.events USING btree (status);
CREATE INDEX IF NOT EXISTS idx_events_category ON public.events USING btree (category);
CREATE INDEX IF NOT EXISTS idx_events_start_date ON public.events USING btree (start_date);
CREATE INDEX IF NOT EXISTS idx_events_is_featured ON public.events USING btree (is_featured) WHERE (is_featured = true);
CREATE INDEX IF NOT EXISTS idx_event_images_event_id ON public.event_images USING btree (event_id);
CREATE INDEX IF NOT EXISTS idx_reservations_date ON public.reservations USING btree (reservation_date);
CREATE INDEX IF NOT EXISTS idx_reservations_terrain_date ON public.reservations USING btree (terrain_id, reservation_date);
CREATE UNIQUE INDEX IF NOT EXISTS idx_reservations_unique_active ON public.reservations USING btree (terrain_id, time_slot_id, reservation_date) WHERE (status = ANY (ARRAY['CONFIRMED'::reservation_status, 'PENDING'::reservation_status]));
CREATE INDEX IF NOT EXISTS idx_reservations_user ON public.reservations USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_reservation_payments_reservation_id ON public.reservation_payments USING btree (reservation_id);
CREATE INDEX IF NOT EXISTS idx_reservation_payments_created_at ON public.reservation_payments USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_client_packages_user_id ON public.client_packages USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_client_packages_status ON public.client_packages USING btree (status);
CREATE INDEX IF NOT EXISTS idx_client_package_sessions_cp_id ON public.client_package_sessions USING btree (client_package_id);
CREATE INDEX IF NOT EXISTS idx_client_package_sessions_reservation ON public.client_package_sessions USING btree (reservation_id);
CREATE INDEX IF NOT EXISTS idx_abonnements_user_id ON public.abonnements USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_abonnements_status ON public.abonnements USING btree (status);
CREATE INDEX IF NOT EXISTS idx_abonnements_terrain_day ON public.abonnements USING btree (terrain_id, day_of_week);
CREATE INDEX IF NOT EXISTS idx_reclamations_user_id ON public.reclamations USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_reclamations_status ON public.reclamations USING btree (status);
CREATE INDEX IF NOT EXISTS idx_reclamations_created_at ON public.reclamations USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_expenses_type ON public.expenses USING btree (expense_type_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON public.expenses USING btree (expense_date);
CREATE INDEX IF NOT EXISTS idx_pos_products_category ON public.pos_products USING btree (category_id);
CREATE INDEX IF NOT EXISTS idx_pos_products_active ON public.pos_products USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_pos_orders_session ON public.pos_orders USING btree (session_id);
CREATE INDEX IF NOT EXISTS idx_pos_orders_status ON public.pos_orders USING btree (status);
CREATE INDEX IF NOT EXISTS idx_pos_orders_created ON public.pos_orders USING btree (created_at);
CREATE INDEX IF NOT EXISTS idx_pos_orders_terrain ON public.pos_orders USING btree (terrain_id);
CREATE INDEX IF NOT EXISTS idx_pos_orders_table ON public.pos_orders USING btree (table_id);
CREATE INDEX IF NOT EXISTS idx_pos_orders_reservation ON public.pos_orders USING btree (reservation_id);
CREATE INDEX IF NOT EXISTS idx_pos_order_items_order ON public.pos_order_items USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_pos_order_payments_order_id ON public.pos_order_payments USING btree (order_id);
CREATE INDEX IF NOT EXISTS idx_pos_purchases_product ON public.pos_purchases USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_pos_purchases_date ON public.pos_purchases USING btree (purchase_date);
CREATE INDEX IF NOT EXISTS idx_pos_purchase_orders_number ON public.pos_purchase_orders USING btree (purchase_number);
CREATE INDEX IF NOT EXISTS idx_pos_purchase_orders_date ON public.pos_purchase_orders USING btree (purchase_date DESC);
CREATE INDEX IF NOT EXISTS idx_pos_purchase_order_items_order ON public.pos_purchase_order_items USING btree (purchase_order_id);
CREATE INDEX IF NOT EXISTS idx_pos_purchase_order_items_product ON public.pos_purchase_order_items USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_pos_stock_movements_product ON public.pos_stock_movements USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_pos_stock_movements_type ON public.pos_stock_movements USING btree (movement_type);
CREATE INDEX IF NOT EXISTS idx_pos_stock_movements_date ON public.pos_stock_movements USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pos_cash_sessions_open ON public.pos_cash_register_sessions USING btree (closed_at) WHERE (closed_at IS NULL);

-- ============================================================================
-- 6. FUNCTIONS
-- ============================================================================

-- is_gerant (requis par les policies)
CREATE OR REPLACE FUNCTION public.is_gerant()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles 
    WHERE id = auth.uid() AND role = 'GERANT'
  );
$function$;

-- get_service_role_key
CREATE OR REPLACE FUNCTION public.get_service_role_key()
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_key text;
BEGIN
  SELECT decrypted_secret INTO v_key
  FROM vault.decrypted_secrets
  WHERE name = 'service_role_key'
  LIMIT 1;
  
  RETURN v_key;
END;
$function$;

-- employee_has_permission
CREATE OR REPLACE FUNCTION public.employee_has_permission(p_employee_id uuid, p_permission text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM employees e
    JOIN profile_permissions pp ON pp.profile_id = e.profile_id
    WHERE e.id = p_employee_id
      AND pp.permission_id = p_permission
      AND e.is_active = TRUE
  );
END;
$function$;

-- hash_employee_password (trigger function)
CREATE OR REPLACE FUNCTION public.hash_employee_password()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF NEW.password_hash IS NOT NULL 
     AND NEW.password_hash != '' 
     AND NEW.password_hash NOT LIKE '$2a$%' 
     AND NEW.password_hash NOT LIKE '$2b$%' THEN
    NEW.password_hash := crypt(NEW.password_hash, gen_salt('bf'));
  END IF;
  RETURN NEW;
END;
$function$;

-- update_updated_at_column
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

-- update_coaches_updated_at
CREATE OR REPLACE FUNCTION public.update_coaches_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$;

-- update_events_updated_at
CREATE OR REPLACE FUNCTION public.update_events_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public'
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

-- update_user_gamification_updated_at
CREATE OR REPLACE FUNCTION public.update_user_gamification_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$function$;

-- update_client_package_sessions_count
CREATE OR REPLACE FUNCTION public.update_client_package_sessions_count()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'INSERT' AND NEW.status = 'USED' THEN
    UPDATE client_packages
    SET sessions_used = sessions_used + 1,
        status = CASE
          WHEN sessions_used + 1 >= sessions_total THEN 'COMPLETED'
          ELSE status
        END
    WHERE id = NEW.client_package_id;
  ELSIF TG_OP = 'UPDATE' AND OLD.status = 'USED' AND NEW.status = 'CANCELLED' THEN
    UPDATE client_packages
    SET sessions_used = GREATEST(sessions_used - 1, 0),
        status = CASE
          WHEN status = 'COMPLETED' THEN 'ACTIVE'
          ELSE status
        END
    WHERE id = NEW.client_package_id;
  ELSIF TG_OP = 'DELETE' AND OLD.status = 'USED' THEN
    UPDATE client_packages
    SET sessions_used = GREATEST(sessions_used - 1, 0),
        status = CASE
          WHEN status = 'COMPLETED' THEN 'ACTIVE'
          ELSE status
        END
    WHERE id = OLD.client_package_id;
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$function$;

-- get_available_slots
CREATE OR REPLACE FUNCTION public.get_available_slots(p_date date)
 RETURNS TABLE(terrain_id bigint, terrain_code text, time_slot_id bigint, start_time time, end_time time, price integer, is_reserved boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY
  SELECT 
    t.id as terrain_id,
    t.code as terrain_code,
    ts.id as time_slot_id,
    ts.start_time,
    ts.end_time,
    ts.price,
    EXISTS (
      SELECT 1 FROM public.reservations r
      WHERE r.terrain_id = t.id 
        AND r.time_slot_id = ts.id
        AND r.reservation_date = p_date
        AND r.status IN ('CONFIRMED', 'PENDING', 'PAID')
    ) as is_reserved
  FROM public.terrains t
  CROSS JOIN public.time_slots ts
  WHERE t.is_active = true AND ts.is_active = true
  ORDER BY ts.start_time, t.code;
END;
$function$;

-- calculate_reservation_points
CREATE OR REPLACE FUNCTION public.calculate_reservation_points(p_time_slot_id bigint)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_start_time TIME;
  v_end_time TIME;
  v_duration_minutes INTEGER;
BEGIN
  SELECT start_time, end_time INTO v_start_time, v_end_time
  FROM time_slots WHERE id = p_time_slot_id;
  
  IF v_start_time IS NULL THEN
    RETURN 0;
  END IF;
  
  v_duration_minutes := EXTRACT(EPOCH FROM (v_end_time - v_start_time)) / 60;
  
  IF v_duration_minutes >= 90 THEN
    RETURN 2;
  ELSE
    RETURN 1;
  END IF;
END;
$function$;

-- add_reservation_points
CREATE OR REPLACE FUNCTION public.add_reservation_points(p_reservation_id bigint)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_user_id UUID;
  v_time_slot_id BIGINT;
  v_points INTEGER;
  v_new_total INTEGER;
BEGIN
  SELECT user_id, time_slot_id INTO v_user_id, v_time_slot_id
  FROM reservations WHERE id = p_reservation_id;
  
  IF v_user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'Reservation not found');
  END IF;
  
  v_points := calculate_reservation_points(v_time_slot_id);
  
  UPDATE profiles 
  SET points = COALESCE(points, 0) + v_points
  WHERE id = v_user_id
  RETURNING points INTO v_new_total;
  
  RETURN json_build_object(
    'success', true,
    'points_earned', v_points,
    'total_points', v_new_total
  );
END;
$function$;

-- get_user_points
CREATE OR REPLACE FUNCTION public.get_user_points()
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_points INTEGER;
BEGIN
  SELECT COALESCE(points, 0) INTO v_points
  FROM profiles WHERE id = auth.uid();
  
  RETURN json_build_object('points', COALESCE(v_points, 0));
END;
$function$;

-- send_otp
CREATE OR REPLACE FUNCTION public.send_otp(p_email text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  v_code text;
  v_expires_at timestamptz;
begin
  v_code := lpad(floor(random() * 10000)::text, 4, '0');
  v_expires_at := now() + interval '10 minutes';
  
  update public.otp_codes 
  set expires_at = now() 
  where email = lower(p_email) 
    and verified = false 
    and expires_at > now();
  
  insert into public.otp_codes (email, code, expires_at)
  values (lower(p_email), v_code, v_expires_at);
  
  return json_build_object(
    'success', true,
    'message', 'Code envoyé à ' || p_email,
    'expires_in_seconds', 600
  );
end $function$;

-- verify_otp
CREATE OR REPLACE FUNCTION public.verify_otp(p_email text, p_code text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
declare
  v_otp_record record;
  v_user_id uuid;
  v_is_new_user boolean := false;
begin
  select * into v_otp_record
  from public.otp_codes
  where email = lower(p_email)
    and verified = false
    and expires_at > now()
  order by created_at desc
  limit 1;
  
  if v_otp_record is null then
    return json_build_object(
      'success', false,
      'error', 'CODE_EXPIRED',
      'message', 'Code expiré ou invalide. Veuillez demander un nouveau code.'
    );
  end if;
  
  if v_otp_record.attempts >= 5 then
    update public.otp_codes set expires_at = now() where id = v_otp_record.id;
    return json_build_object(
      'success', false,
      'error', 'TOO_MANY_ATTEMPTS',
      'message', 'Trop de tentatives. Veuillez demander un nouveau code.'
    );
  end if;
  
  update public.otp_codes 
  set attempts = attempts + 1 
  where id = v_otp_record.id;
  
  if v_otp_record.code != p_code then
    return json_build_object(
      'success', false,
      'error', 'INVALID_CODE',
      'message', 'Code incorrect. ' || (4 - v_otp_record.attempts) || ' tentatives restantes.',
      'attempts_remaining', 4 - v_otp_record.attempts
    );
  end if;
  
  update public.otp_codes 
  set verified = true 
  where id = v_otp_record.id;
  
  select id into v_user_id
  from auth.users
  where email = lower(p_email)
  limit 1;
  
  if v_user_id is null then
    v_is_new_user := true;
  end if;
  
  return json_build_object(
    'success', true,
    'message', 'Code vérifié avec succès',
    'is_new_user', v_is_new_user,
    'user_id', v_user_id
  );
end $function$;

-- verify_employee_password
CREATE OR REPLACE FUNCTION public.verify_employee_password(p_username varchar, p_password varchar)
 RETURNS TABLE(id uuid, username varchar, full_name varchar, role varchar, is_active boolean)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY
  SELECT 
    e.id,
    e.username,
    e.full_name,
    e.role,
    e.is_active
  FROM public.employees e
  WHERE e.username = p_username
    AND e.password_hash = crypt(p_password, e.password_hash)
    AND e.is_active = true;
  
  UPDATE public.employees 
  SET last_login_at = NOW() 
  WHERE employees.username = p_username 
    AND employees.password_hash = crypt(p_password, employees.password_hash);
END;
$function$;

-- verify_employee_password_v2
CREATE OR REPLACE FUNCTION public.verify_employee_password_v2(p_username text, p_password text)
 RETURNS TABLE(id uuid, username text, full_name text, role text, is_active boolean, profile_id uuid, profile_name text, profile_display_name text, base_route text, hierarchy_level integer, permissions text[])
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    e.id,
    e.username::TEXT,
    e.full_name::TEXT,
    e.role::TEXT,
    e.is_active,
    e.profile_id,
    p.name::TEXT AS profile_name,
    p.display_name::TEXT AS profile_display_name,
    p.base_route::TEXT,
    p.hierarchy_level,
    COALESCE(
      ARRAY(
        SELECT pp.permission_id::TEXT
        FROM profile_permissions pp
        WHERE pp.profile_id = e.profile_id
        ORDER BY pp.permission_id
      ),
      ARRAY[]::TEXT[]
    ) AS permissions
  FROM employees e
  LEFT JOIN employee_profiles p ON p.id = e.profile_id
  WHERE e.username = p_username
    AND e.password_hash = crypt(p_password, e.password_hash)
    AND e.is_active = TRUE;
END;
$function$;

-- verify_employee_login
CREATE OR REPLACE FUNCTION public.verify_employee_login(p_username text, p_password text)
 RETURNS TABLE(id uuid, username text, full_name text, role text, is_active boolean, profile_id uuid, profile_name text, profile_display_name text, base_route text, hierarchy_level integer, permissions text[])
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    e.id,
    e.username::TEXT,
    e.full_name::TEXT,
    e.role::TEXT,
    e.is_active,
    e.profile_id,
    p.name::TEXT AS profile_name,
    p.display_name::TEXT AS profile_display_name,
    p.base_route::TEXT,
    p.hierarchy_level,
    COALESCE(
      ARRAY(
        SELECT pp.permission_id::TEXT
        FROM profile_permissions pp
        WHERE pp.profile_id = e.profile_id
        ORDER BY pp.permission_id
      ),
      ARRAY[]::TEXT[]
    ) AS permissions
  FROM employees e
  LEFT JOIN employee_profiles p ON p.id = e.profile_id
  WHERE e.username = p_username
    AND e.password_hash = crypt(p_password, e.password_hash)
    AND e.is_active = TRUE;
END;
$function$;

-- ⚠️ notify_event_published — CONTIENT URL HARDCODÉE À REMPLACER
CREATE OR REPLACE FUNCTION public.notify_event_published()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_title text;
  v_body text;
  v_payload jsonb;
  v_start_date text;
  v_service_key text;
BEGIN
  IF NEW.status = 'PUBLISHED' AND (OLD.status IS NULL OR OLD.status != 'PUBLISHED') THEN
    v_service_key := public.get_service_role_key();
    IF v_service_key IS NULL THEN
      RAISE WARNING 'service_role_key not found in vault';
      RETURN NEW;
    END IF;

    v_start_date := to_char(NEW.start_date, 'DD/MM/YYYY à HH24:MI');
    
    v_title := 'Nouvel événement 🎉 ' || NEW.title;
    v_body := COALESCE(NEW.description, 'Un nouvel événement est disponible !') 
              || ' - ' || v_start_date 
              || ' à ' || COALESCE(NEW.location, 'PadelHouse Club');

    v_payload := jsonb_build_object(
      'type', 'event_published',
      'title', v_title,
      'body', v_body,
      'data', jsonb_build_object(
        'event_id', NEW.id::text,
        'event_title', NEW.title,
        'start_date', NEW.start_date::text
      ),
      'target_type', 'all',
      'target_user_ids', '[]'::jsonb,
      'sent_by', 'system_trigger'
    );

    -- ⚠️ REMPLACER qxauriiupckwouucmgkr PAR LE NOUVEAU PROJECT_ID
    PERFORM net.http_post(
      url := 'https://qxauriiupckwouucmgkr.supabase.co/functions/v1/send-push-notification',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || v_service_key
      ),
      body := v_payload
    );

    PERFORM net.http_post(
      url := 'https://qxauriiupckwouucmgkr.supabase.co/functions/v1/send-email-notification',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || v_service_key
      ),
      body := v_payload
    );
  END IF;

  RETURN NEW;
END;
$function$;

-- ⚠️ notify_reservation_confirmed — CONTIENT URL HARDCODÉE À REMPLACER
CREATE OR REPLACE FUNCTION public.notify_reservation_confirmed()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_terrain_code text;
  v_start_time text;
  v_end_time text;
  v_user_name text;
  v_title text;
  v_body text;
  v_payload jsonb;
  v_service_key text;
BEGIN
  IF NEW.status = 'CONFIRMED' AND (OLD.status IS NULL OR OLD.status != 'CONFIRMED') THEN
    v_service_key := public.get_service_role_key();
    IF v_service_key IS NULL THEN
      RAISE WARNING 'service_role_key not found in vault';
      RETURN NEW;
    END IF;

    SELECT code INTO v_terrain_code FROM public.terrains WHERE id = NEW.terrain_id;
    SELECT 
      to_char(start_time, 'HH24:MI'), 
      to_char(end_time, 'HH24:MI')
    INTO v_start_time, v_end_time 
    FROM public.time_slots WHERE id = NEW.time_slot_id;

    v_title := 'Réservation confirmée ✅';
    v_body := 'Votre réservation sur ' || COALESCE(v_terrain_code, 'Terrain') 
              || ' le ' || to_char(NEW.reservation_date, 'DD/MM/YYYY') 
              || ' de ' || COALESCE(v_start_time, '') || ' à ' || COALESCE(v_end_time, '') 
              || ' est confirmée.';

    v_payload := jsonb_build_object(
      'type', 'reservation_confirmed',
      'title', v_title,
      'body', v_body,
      'data', jsonb_build_object(
        'reservation_id', NEW.id::text,
        'terrain', COALESCE(v_terrain_code, ''),
        'date', NEW.reservation_date::text,
        'start_time', COALESCE(v_start_time, '')
      ),
      'target_type', 'single',
      'target_user_ids', jsonb_build_array(NEW.user_id::text),
      'sent_by', 'system_trigger'
    );

    -- ⚠️ REMPLACER qxauriiupckwouucmgkr PAR LE NOUVEAU PROJECT_ID
    PERFORM net.http_post(
      url := 'https://qxauriiupckwouucmgkr.supabase.co/functions/v1/send-push-notification',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || v_service_key
      ),
      body := v_payload
    );

    PERFORM net.http_post(
      url := 'https://qxauriiupckwouucmgkr.supabase.co/functions/v1/send-email-notification',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer ' || v_service_key
      ),
      body := v_payload
    );
  END IF;

  RETURN NEW;
END;
$function$;

-- ============================================================================
-- 7. TRIGGERS
-- ============================================================================
CREATE OR REPLACE TRIGGER reservations_updated_at
  BEFORE UPDATE ON public.reservations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE OR REPLACE TRIGGER trg_notify_reservation_confirmed
  AFTER INSERT OR UPDATE ON public.reservations
  FOR EACH ROW EXECUTE FUNCTION notify_reservation_confirmed();

CREATE OR REPLACE TRIGGER events_updated_at
  BEFORE UPDATE ON public.events
  FOR EACH ROW EXECUTE FUNCTION update_events_updated_at();

CREATE OR REPLACE TRIGGER trg_notify_event_published
  AFTER INSERT OR UPDATE ON public.events
  FOR EACH ROW EXECUTE FUNCTION notify_event_published();

CREATE OR REPLACE TRIGGER coaches_updated_at_trigger
  BEFORE UPDATE ON public.coaches
  FOR EACH ROW EXECUTE FUNCTION update_coaches_updated_at();

CREATE OR REPLACE TRIGGER trg_hash_employee_password
  BEFORE INSERT OR UPDATE ON public.employees
  FOR EACH ROW EXECUTE FUNCTION hash_employee_password();

CREATE OR REPLACE TRIGGER trg_update_package_sessions_count
  AFTER INSERT OR UPDATE OR DELETE ON public.client_package_sessions
  FOR EACH ROW EXECUTE FUNCTION update_client_package_sessions_count();

-- ============================================================================
-- 8. RLS (Enable + Policies)
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE public.terrains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coaches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expense_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.otp_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fcm_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservation_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_package_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.package_time_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.abonnements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reclamations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_cash_register_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_order_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_expenses ENABLE ROW LEVEL SECURITY;

-- Policies: terrains
CREATE POLICY "Public read access" ON public.terrains FOR SELECT USING (true);
CREATE POLICY "Terrains: public read" ON public.terrains FOR SELECT USING (true);
CREATE POLICY "Terrains: gerant write" ON public.terrains FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'GERANT'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'GERANT'));

-- Policies: time_slots
CREATE POLICY "Public read access" ON public.time_slots FOR SELECT USING (true);
CREATE POLICY "time_slots_select_anon" ON public.time_slots FOR SELECT TO anon USING (true);
CREATE POLICY "time_slots_select_authenticated" ON public.time_slots FOR SELECT TO authenticated USING (true);

-- Policies: permissions
CREATE POLICY "Allow anon full access on permissions" ON public.permissions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read on permissions" ON public.permissions FOR SELECT USING (true);

-- Policies: employee_profiles
CREATE POLICY "Allow anon full access on employee_profiles" ON public.employee_profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read on employee_profiles" ON public.employee_profiles FOR SELECT USING (true);

-- Policies: coaches
CREATE POLICY "Anyone can view active coaches" ON public.coaches FOR SELECT USING (is_active = true);
CREATE POLICY "Authenticated users can view all coaches" ON public.coaches FOR SELECT TO authenticated USING (true);
CREATE POLICY "Service role can manage coaches" ON public.coaches FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Policies: payment_methods
CREATE POLICY "Allow authenticated manage" ON public.payment_methods FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated read" ON public.payment_methods FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow public read" ON public.payment_methods FOR SELECT TO anon USING (true);

-- Policies: expense_types
CREATE POLICY "Backoffice: can manage expense_types" ON public.expense_types FOR ALL USING (true);
CREATE POLICY "Backoffice: can read expense_types" ON public.expense_types FOR SELECT USING (true);

-- Policies: notification_logs
CREATE POLICY "Authenticated can read notification_logs" ON public.notification_logs FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Service role full access on notification_logs" ON public.notification_logs FOR ALL USING (auth.role() = 'service_role');

-- Policies: packages
CREATE POLICY "packages_all" ON public.packages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "packages_select" ON public.packages FOR SELECT USING (true);

-- Policies: profiles
CREATE POLICY "Backoffice: can read all profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Profiles: gerant can read all" ON public.profiles FOR SELECT USING (is_gerant());
CREATE POLICY "Profiles: gerant can update all" ON public.profiles FOR UPDATE USING (is_gerant()) WITH CHECK (is_gerant());
CREATE POLICY "Profiles: user can insert own" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Profiles: user can read own" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Profiles: user can update own" ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Policies: employees
CREATE POLICY "Allow read for authenticated" ON public.employees FOR SELECT USING (true);
CREATE POLICY "Backoffice: can delete employees" ON public.employees FOR DELETE USING (true);
CREATE POLICY "Backoffice: can insert employees" ON public.employees FOR INSERT WITH CHECK (true);
CREATE POLICY "Backoffice: can read employees" ON public.employees FOR SELECT USING (true);
CREATE POLICY "Backoffice: can update employees" ON public.employees FOR UPDATE USING (true);

-- Policies: profile_permissions
CREATE POLICY "Allow anon full access on profile_permissions" ON public.profile_permissions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow public read on profile_permissions" ON public.profile_permissions FOR SELECT USING (true);

-- Policies: fcm_tokens
CREATE POLICY "Service role full access on fcm_tokens" ON public.fcm_tokens FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "Users can manage their own FCM tokens" ON public.fcm_tokens FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Policies: events
CREATE POLICY "Allow all for anon" ON public.events FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Managers can manage events" ON public.events FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'));
CREATE POLICY "Published events are viewable by everyone" ON public.events FOR SELECT USING (status = 'PUBLISHED');

-- Policies: event_images
CREATE POLICY "Allow all for anon" ON public.event_images FOR ALL TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Event images are viewable for published events" ON public.event_images FOR SELECT
  USING (EXISTS (SELECT 1 FROM events WHERE events.id = event_images.event_id AND events.status = 'PUBLISHED'));
CREATE POLICY "Managers can manage event images" ON public.event_images FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'));

-- Policies: reservations (pas de policy car gérée via service_role côté app)
-- Si nécessaire, ajouter des policies ici

-- Policies: reservation_payments
CREATE POLICY "Allow authenticated manage" ON public.reservation_payments FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow authenticated read" ON public.reservation_payments FOR SELECT TO authenticated USING (true);

-- Policies: client_packages
CREATE POLICY "client_packages_all" ON public.client_packages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "client_packages_select" ON public.client_packages FOR SELECT USING (true);

-- Policies: client_package_sessions
CREATE POLICY "client_package_sessions_all" ON public.client_package_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "client_package_sessions_select" ON public.client_package_sessions FOR SELECT USING (true);

-- Policies: package_time_slots
CREATE POLICY "package_time_slots_all" ON public.package_time_slots FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "package_time_slots_select" ON public.package_time_slots FOR SELECT USING (true);

-- Policies: abonnements
CREATE POLICY "abonnements_all_for_authenticated" ON public.abonnements FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Policies: reclamations
CREATE POLICY "Users can create reclamations" ON public.reclamations FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own reclamations" ON public.reclamations FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own pending reclamations" ON public.reclamations FOR UPDATE USING (auth.uid() = user_id AND status::text = 'pending');

-- Policies: expenses
CREATE POLICY "Backoffice: can read expenses" ON public.expenses FOR SELECT USING (true);
CREATE POLICY "Backoffice: can insert expenses" ON public.expenses FOR INSERT WITH CHECK (true);
CREATE POLICY "Backoffice: can update expenses" ON public.expenses FOR UPDATE USING (true);
CREATE POLICY "Backoffice: can delete expenses" ON public.expenses FOR DELETE USING (true);

-- Policies: POS tables
CREATE POLICY "Allow all for anon" ON public.pos_categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated" ON public.pos_tables FOR ALL USING (true);
CREATE POLICY "Allow all for anon" ON public.pos_cash_register_sessions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_order_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_purchase_orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_purchase_order_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_purchases FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_stock_movements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated" ON public.pos_expenses FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for anon" ON public.pos_order_payments FOR ALL USING (true) WITH CHECK (true);

-- ============================================================================
-- 9. STORAGE BUCKETS
-- ============================================================================
INSERT INTO storage.buckets (id, name, public) VALUES ('avatars', 'avatars', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('reclamations', 'reclamations', false) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('event-images', 'event-images', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('app-assets', 'app-assets', true) ON CONFLICT (id) DO NOTHING;

-- Storage Policies
CREATE POLICY "Anyone can view avatars" ON storage.objects FOR SELECT USING (bucket_id = 'avatars');
CREATE POLICY "Users can upload their own avatar" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "Users can update their own avatar" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "Users can delete their own avatar" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "Event images are publicly accessible" ON storage.objects FOR SELECT USING (bucket_id = 'event-images');
CREATE POLICY "Managers can upload event images" ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'event-images' AND EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'));
CREATE POLICY "Managers can delete event images" ON storage.objects FOR DELETE
  USING (bucket_id = 'event-images' AND EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'));
CREATE POLICY "Allow anon upload event images" ON storage.objects FOR INSERT TO anon WITH CHECK (bucket_id = 'event-images');
CREATE POLICY "Allow anon update event images" ON storage.objects FOR UPDATE TO anon USING (bucket_id = 'event-images');
CREATE POLICY "Allow anon delete event images" ON storage.objects FOR DELETE TO anon USING (bucket_id = 'event-images');

CREATE POLICY "Users can upload reclamation photos" ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'reclamations' AND auth.uid() IS NOT NULL AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "Users can view own reclamation photos" ON storage.objects FOR SELECT
  USING (bucket_id = 'reclamations' AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "Users can delete own reclamation photos" ON storage.objects FOR DELETE
  USING (bucket_id = 'reclamations' AND (storage.foldername(name))[1] = auth.uid()::text);

CREATE POLICY "Public read access for app-assets" ON storage.objects FOR SELECT USING (bucket_id = 'app-assets');
CREATE POLICY "Gerant can manage app-assets" ON storage.objects FOR ALL TO authenticated
  USING (bucket_id = 'app-assets' AND EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'))
  WITH CHECK (bucket_id = 'app-assets' AND EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'GERANT'));

-- ============================================================================
-- 10. SEED DATA (données de configuration à conserver)
-- ============================================================================

-- Permissions (27 entrées)
INSERT INTO public.permissions (id, display_name, description, category, sort_order) VALUES
  ('dashboard.view', 'Voir le tableau de bord', 'Accès au tableau de bord principal', 'Dashboard', 1),
  ('caisse.view', 'Accéder à la caisse', 'Ouvrir et utiliser la caisse', 'Caisse', 10),
  ('caisse.manage', 'Gérer la caisse', 'Fermer la caisse, annuler des commandes', 'Caisse', 11),
  ('reservations.view', 'Voir les réservations', 'Consulter les réservations', 'Réservations', 20),
  ('reservations.manage', 'Gérer les réservations', 'Créer, modifier, annuler des réservations', 'Réservations', 21),
  ('terrains.view', 'Voir les terrains', 'Consulter les terrains', 'Terrains', 30),
  ('terrains.manage', 'Gérer les terrains', 'Créer, modifier les terrains', 'Terrains', 31),
  ('creneaux.view', 'Voir les créneaux', 'Consulter les créneaux horaires', 'Créneaux', 40),
  ('creneaux.manage', 'Gérer les créneaux', 'Créer, modifier les créneaux', 'Créneaux', 41),
  ('joueurs.view', 'Voir les joueurs', 'Consulter la liste des joueurs', 'Joueurs', 50),
  ('joueurs.manage', 'Gérer les joueurs', 'Créer, modifier les joueurs', 'Joueurs', 51),
  ('produits.view', 'Voir les produits', 'Consulter les produits et le stock', 'Produits', 60),
  ('produits.manage', 'Gérer les produits', 'Créer, modifier les produits et le stock', 'Produits', 61),
  ('depenses.view', 'Voir les dépenses', 'Consulter les dépenses', 'Dépenses', 70),
  ('depenses.manage', 'Gérer les dépenses', 'Créer, modifier les dépenses', 'Dépenses', 71),
  ('employes.view', 'Voir les employés', 'Consulter la liste des employés', 'Employés', 80),
  ('employes.manage', 'Gérer les employés', 'Créer, modifier, supprimer des employés', 'Employés', 81),
  ('statistiques.view', 'Voir les statistiques', 'Accès aux rapports et statistiques', 'Statistiques', 90),
  ('evenements.view', 'Voir les événements', 'Consulter les événements', 'Événements', 95),
  ('evenements.manage', 'Gérer les événements', 'Créer, modifier, supprimer des événements', 'Événements', 96),
  ('parametres.manage', 'Gérer les paramètres', 'Modifier les paramètres de l''application', 'Paramètres', 100),
  ('abonnements.view', 'Voir les abonnements', 'Consulter la liste des abonnements récurrents', 'Abonnements', 110),
  ('notifications.view', 'Voir les notifications', 'Consulter l''historique des notifications push', 'Notifications', 110),
  ('notifications.manage', 'Gérer les notifications', 'Envoyer des notifications push aux joueurs', 'Notifications', 111),
  ('abonnements.manage', 'Gérer les abonnements', 'Créer, modifier, supprimer des abonnements', 'Abonnements', 111),
  ('packages.view', 'Voir les packages', 'Permet de voir la liste des packages et attributions', 'Packages', 130),
  ('packages.manage', 'Gérer les packages', 'Permet de créer, modifier, supprimer et attribuer des packages', 'Packages', 131)
ON CONFLICT (id) DO NOTHING;

-- Packages (données de configuration)
INSERT INTO public.packages (name, description, total_sessions, price, regular_price, duration_minutes, is_active) VALUES
  ('Pack 12 Seances', 'Pack 12 Séances 1 heure', 12, 100000, 120000, 60, true)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- FIN DE L'EXPORT
-- ============================================================================
-- 
-- CHECKLIST POST-IMPORT:
-- 1. Remplacer 'qxauriiupckwouucmgkr' par le nouveau project_id dans ce fichier
-- 2. Configurer le secret 'service_role_key' dans Vault
-- 3. Redéployer les Edge Functions (6)
-- 4. Mettre à jour .env avec nouvelles URL/clés
-- 5. Configurer SMTP + OAuth dans le dashboard
-- 6. Copier les fichiers du bucket 'app-assets' manuellement
-- ============================================================================
